name: Submit Application

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' }}

    steps:
      - uses: actions/checkout@v4
      - name: Run submission script
        env:
          SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
        run: python3 submit.py
